/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedLayoutRouteImport } from './routes/_protectedLayout'
import { Route as AuthLayoutRouteImport } from './routes/_authLayout'
import { Route as AuthLayoutIndexRouteImport } from './routes/_authLayout/index'
import { Route as AuthLayoutRegisterRouteImport } from './routes/_authLayout/register'
import { Route as ProtectedLayoutProfileIndexRouteImport } from './routes/_protectedLayout/profile/index'
import { Route as ProtectedLayoutDashboardIndexRouteImport } from './routes/_protectedLayout/dashboard/index'
import { Route as ProtectedLayoutCategoriesIndexRouteImport } from './routes/_protectedLayout/categories/index'
import { Route as ProtectedLayoutBorrowingsIndexRouteImport } from './routes/_protectedLayout/borrowings/index'
import { Route as ProtectedLayoutBooksIndexRouteImport } from './routes/_protectedLayout/books/index'

const ProtectedLayoutRoute = ProtectedLayoutRouteImport.update({
  id: '/_protectedLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutIndexRoute = AuthLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutRegisterRoute = AuthLayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const ProtectedLayoutProfileIndexRoute =
  ProtectedLayoutProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutDashboardIndexRoute =
  ProtectedLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutCategoriesIndexRoute =
  ProtectedLayoutCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutBorrowingsIndexRoute =
  ProtectedLayoutBorrowingsIndexRouteImport.update({
    id: '/borrowings/',
    path: '/borrowings/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutBooksIndexRoute =
  ProtectedLayoutBooksIndexRouteImport.update({
    id: '/books/',
    path: '/books/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthLayoutIndexRoute
  '/register': typeof AuthLayoutRegisterRoute
  '/books/': typeof ProtectedLayoutBooksIndexRoute
  '/borrowings/': typeof ProtectedLayoutBorrowingsIndexRoute
  '/categories/': typeof ProtectedLayoutCategoriesIndexRoute
  '/dashboard/': typeof ProtectedLayoutDashboardIndexRoute
  '/profile/': typeof ProtectedLayoutProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthLayoutIndexRoute
  '/register': typeof AuthLayoutRegisterRoute
  '/books': typeof ProtectedLayoutBooksIndexRoute
  '/borrowings': typeof ProtectedLayoutBorrowingsIndexRoute
  '/categories': typeof ProtectedLayoutCategoriesIndexRoute
  '/dashboard': typeof ProtectedLayoutDashboardIndexRoute
  '/profile': typeof ProtectedLayoutProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authLayout': typeof AuthLayoutRouteWithChildren
  '/_protectedLayout': typeof ProtectedLayoutRouteWithChildren
  '/_authLayout/register': typeof AuthLayoutRegisterRoute
  '/_authLayout/': typeof AuthLayoutIndexRoute
  '/_protectedLayout/books/': typeof ProtectedLayoutBooksIndexRoute
  '/_protectedLayout/borrowings/': typeof ProtectedLayoutBorrowingsIndexRoute
  '/_protectedLayout/categories/': typeof ProtectedLayoutCategoriesIndexRoute
  '/_protectedLayout/dashboard/': typeof ProtectedLayoutDashboardIndexRoute
  '/_protectedLayout/profile/': typeof ProtectedLayoutProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/books/'
    | '/borrowings/'
    | '/categories/'
    | '/dashboard/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/books'
    | '/borrowings'
    | '/categories'
    | '/dashboard'
    | '/profile'
  id:
    | '__root__'
    | '/_authLayout'
    | '/_protectedLayout'
    | '/_authLayout/register'
    | '/_authLayout/'
    | '/_protectedLayout/books/'
    | '/_protectedLayout/borrowings/'
    | '/_protectedLayout/categories/'
    | '/_protectedLayout/dashboard/'
    | '/_protectedLayout/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protectedLayout': {
      id: '/_protectedLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout/': {
      id: '/_authLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/register': {
      id: '/_authLayout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthLayoutRegisterRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_protectedLayout/profile/': {
      id: '/_protectedLayout/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProtectedLayoutProfileIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/dashboard/': {
      id: '/_protectedLayout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedLayoutDashboardIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/categories/': {
      id: '/_protectedLayout/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof ProtectedLayoutCategoriesIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/borrowings/': {
      id: '/_protectedLayout/borrowings/'
      path: '/borrowings'
      fullPath: '/borrowings/'
      preLoaderRoute: typeof ProtectedLayoutBorrowingsIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/books/': {
      id: '/_protectedLayout/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof ProtectedLayoutBooksIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutRegisterRoute: typeof AuthLayoutRegisterRoute
  AuthLayoutIndexRoute: typeof AuthLayoutIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutRegisterRoute: AuthLayoutRegisterRoute,
  AuthLayoutIndexRoute: AuthLayoutIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface ProtectedLayoutRouteChildren {
  ProtectedLayoutBooksIndexRoute: typeof ProtectedLayoutBooksIndexRoute
  ProtectedLayoutBorrowingsIndexRoute: typeof ProtectedLayoutBorrowingsIndexRoute
  ProtectedLayoutCategoriesIndexRoute: typeof ProtectedLayoutCategoriesIndexRoute
  ProtectedLayoutDashboardIndexRoute: typeof ProtectedLayoutDashboardIndexRoute
  ProtectedLayoutProfileIndexRoute: typeof ProtectedLayoutProfileIndexRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedLayoutBooksIndexRoute: ProtectedLayoutBooksIndexRoute,
  ProtectedLayoutBorrowingsIndexRoute: ProtectedLayoutBorrowingsIndexRoute,
  ProtectedLayoutCategoriesIndexRoute: ProtectedLayoutCategoriesIndexRoute,
  ProtectedLayoutDashboardIndexRoute: ProtectedLayoutDashboardIndexRoute,
  ProtectedLayoutProfileIndexRoute: ProtectedLayoutProfileIndexRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
