/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicLayoutRouteImport } from './routes/_publicLayout'
import { Route as ProtectedLayoutRouteImport } from './routes/_protectedLayout'
import { Route as AuthLayoutRouteImport } from './routes/_authLayout'
import { Route as PublicLayoutIndexRouteImport } from './routes/_publicLayout/index'
import { Route as AuthLayoutRegisterRouteImport } from './routes/_authLayout/register'
import { Route as AuthLayoutLoginRouteImport } from './routes/_authLayout/login'
import { Route as PublicLayoutServicesIndexRouteImport } from './routes/_publicLayout/services/index'
import { Route as PublicLayoutOurMissionIndexRouteImport } from './routes/_publicLayout/our-mission/index'
import { Route as PublicLayoutCollectionsIndexRouteImport } from './routes/_publicLayout/collections/index'
import { Route as PublicLayoutAboutUsIndexRouteImport } from './routes/_publicLayout/about-us/index'
import { Route as ProtectedLayoutUsersIndexRouteImport } from './routes/_protectedLayout/users/index'
import { Route as ProtectedLayoutShkollaIndexRouteImport } from './routes/_protectedLayout/shkolla/index'
import { Route as ProtectedLayoutProfileIndexRouteImport } from './routes/_protectedLayout/profile/index'
import { Route as ProtectedLayoutGroupIndexRouteImport } from './routes/_protectedLayout/group/index'
import { Route as ProtectedLayoutDepartmentIndexRouteImport } from './routes/_protectedLayout/department/index'
import { Route as ProtectedLayoutDashboardIndexRouteImport } from './routes/_protectedLayout/dashboard/index'
import { Route as ProtectedLayoutCategoriesIndexRouteImport } from './routes/_protectedLayout/categories/index'
import { Route as ProtectedLayoutBorrowingsIndexRouteImport } from './routes/_protectedLayout/borrowings/index'
import { Route as ProtectedLayoutBooksIndexRouteImport } from './routes/_protectedLayout/books/index'
import { Route as PublicLayoutCollectionsIdIndexRouteImport } from './routes/_publicLayout/collections/$id/index'
import { Route as ProtectedLayoutBooksAddIndexRouteImport } from './routes/_protectedLayout/books/add/index'
import { Route as ProtectedLayoutBooksIdIndexRouteImport } from './routes/_protectedLayout/books/$id/index'

const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_publicLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLayoutRoute = ProtectedLayoutRouteImport.update({
  id: '/_protectedLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutIndexRoute = PublicLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const AuthLayoutRegisterRoute = AuthLayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutLoginRoute = AuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const PublicLayoutServicesIndexRoute =
  PublicLayoutServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const PublicLayoutOurMissionIndexRoute =
  PublicLayoutOurMissionIndexRouteImport.update({
    id: '/our-mission/',
    path: '/our-mission/',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const PublicLayoutCollectionsIndexRoute =
  PublicLayoutCollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const PublicLayoutAboutUsIndexRoute =
  PublicLayoutAboutUsIndexRouteImport.update({
    id: '/about-us/',
    path: '/about-us/',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const ProtectedLayoutUsersIndexRoute =
  ProtectedLayoutUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutShkollaIndexRoute =
  ProtectedLayoutShkollaIndexRouteImport.update({
    id: '/shkolla/',
    path: '/shkolla/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutProfileIndexRoute =
  ProtectedLayoutProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutGroupIndexRoute =
  ProtectedLayoutGroupIndexRouteImport.update({
    id: '/group/',
    path: '/group/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutDepartmentIndexRoute =
  ProtectedLayoutDepartmentIndexRouteImport.update({
    id: '/department/',
    path: '/department/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutDashboardIndexRoute =
  ProtectedLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutCategoriesIndexRoute =
  ProtectedLayoutCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutBorrowingsIndexRoute =
  ProtectedLayoutBorrowingsIndexRouteImport.update({
    id: '/borrowings/',
    path: '/borrowings/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutBooksIndexRoute =
  ProtectedLayoutBooksIndexRouteImport.update({
    id: '/books/',
    path: '/books/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const PublicLayoutCollectionsIdIndexRoute =
  PublicLayoutCollectionsIdIndexRouteImport.update({
    id: '/collections/$id/',
    path: '/collections/$id/',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const ProtectedLayoutBooksAddIndexRoute =
  ProtectedLayoutBooksAddIndexRouteImport.update({
    id: '/books/add/',
    path: '/books/add/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutBooksIdIndexRoute =
  ProtectedLayoutBooksIdIndexRouteImport.update({
    id: '/books/$id/',
    path: '/books/$id/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicLayoutIndexRoute
  '/login': typeof AuthLayoutLoginRoute
  '/register': typeof AuthLayoutRegisterRoute
  '/books/': typeof ProtectedLayoutBooksIndexRoute
  '/borrowings/': typeof ProtectedLayoutBorrowingsIndexRoute
  '/categories/': typeof ProtectedLayoutCategoriesIndexRoute
  '/dashboard/': typeof ProtectedLayoutDashboardIndexRoute
  '/department/': typeof ProtectedLayoutDepartmentIndexRoute
  '/group/': typeof ProtectedLayoutGroupIndexRoute
  '/profile/': typeof ProtectedLayoutProfileIndexRoute
  '/shkolla/': typeof ProtectedLayoutShkollaIndexRoute
  '/users/': typeof ProtectedLayoutUsersIndexRoute
  '/about-us/': typeof PublicLayoutAboutUsIndexRoute
  '/collections/': typeof PublicLayoutCollectionsIndexRoute
  '/our-mission/': typeof PublicLayoutOurMissionIndexRoute
  '/services/': typeof PublicLayoutServicesIndexRoute
  '/books/$id/': typeof ProtectedLayoutBooksIdIndexRoute
  '/books/add/': typeof ProtectedLayoutBooksAddIndexRoute
  '/collections/$id/': typeof PublicLayoutCollectionsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicLayoutIndexRoute
  '/login': typeof AuthLayoutLoginRoute
  '/register': typeof AuthLayoutRegisterRoute
  '/books': typeof ProtectedLayoutBooksIndexRoute
  '/borrowings': typeof ProtectedLayoutBorrowingsIndexRoute
  '/categories': typeof ProtectedLayoutCategoriesIndexRoute
  '/dashboard': typeof ProtectedLayoutDashboardIndexRoute
  '/department': typeof ProtectedLayoutDepartmentIndexRoute
  '/group': typeof ProtectedLayoutGroupIndexRoute
  '/profile': typeof ProtectedLayoutProfileIndexRoute
  '/shkolla': typeof ProtectedLayoutShkollaIndexRoute
  '/users': typeof ProtectedLayoutUsersIndexRoute
  '/about-us': typeof PublicLayoutAboutUsIndexRoute
  '/collections': typeof PublicLayoutCollectionsIndexRoute
  '/our-mission': typeof PublicLayoutOurMissionIndexRoute
  '/services': typeof PublicLayoutServicesIndexRoute
  '/books/$id': typeof ProtectedLayoutBooksIdIndexRoute
  '/books/add': typeof ProtectedLayoutBooksAddIndexRoute
  '/collections/$id': typeof PublicLayoutCollectionsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authLayout': typeof AuthLayoutRouteWithChildren
  '/_protectedLayout': typeof ProtectedLayoutRouteWithChildren
  '/_publicLayout': typeof PublicLayoutRouteWithChildren
  '/_authLayout/login': typeof AuthLayoutLoginRoute
  '/_authLayout/register': typeof AuthLayoutRegisterRoute
  '/_publicLayout/': typeof PublicLayoutIndexRoute
  '/_protectedLayout/books/': typeof ProtectedLayoutBooksIndexRoute
  '/_protectedLayout/borrowings/': typeof ProtectedLayoutBorrowingsIndexRoute
  '/_protectedLayout/categories/': typeof ProtectedLayoutCategoriesIndexRoute
  '/_protectedLayout/dashboard/': typeof ProtectedLayoutDashboardIndexRoute
  '/_protectedLayout/department/': typeof ProtectedLayoutDepartmentIndexRoute
  '/_protectedLayout/group/': typeof ProtectedLayoutGroupIndexRoute
  '/_protectedLayout/profile/': typeof ProtectedLayoutProfileIndexRoute
  '/_protectedLayout/shkolla/': typeof ProtectedLayoutShkollaIndexRoute
  '/_protectedLayout/users/': typeof ProtectedLayoutUsersIndexRoute
  '/_publicLayout/about-us/': typeof PublicLayoutAboutUsIndexRoute
  '/_publicLayout/collections/': typeof PublicLayoutCollectionsIndexRoute
  '/_publicLayout/our-mission/': typeof PublicLayoutOurMissionIndexRoute
  '/_publicLayout/services/': typeof PublicLayoutServicesIndexRoute
  '/_protectedLayout/books/$id/': typeof ProtectedLayoutBooksIdIndexRoute
  '/_protectedLayout/books/add/': typeof ProtectedLayoutBooksAddIndexRoute
  '/_publicLayout/collections/$id/': typeof PublicLayoutCollectionsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/books/'
    | '/borrowings/'
    | '/categories/'
    | '/dashboard/'
    | '/department/'
    | '/group/'
    | '/profile/'
    | '/shkolla/'
    | '/users/'
    | '/about-us/'
    | '/collections/'
    | '/our-mission/'
    | '/services/'
    | '/books/$id/'
    | '/books/add/'
    | '/collections/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/books'
    | '/borrowings'
    | '/categories'
    | '/dashboard'
    | '/department'
    | '/group'
    | '/profile'
    | '/shkolla'
    | '/users'
    | '/about-us'
    | '/collections'
    | '/our-mission'
    | '/services'
    | '/books/$id'
    | '/books/add'
    | '/collections/$id'
  id:
    | '__root__'
    | '/_authLayout'
    | '/_protectedLayout'
    | '/_publicLayout'
    | '/_authLayout/login'
    | '/_authLayout/register'
    | '/_publicLayout/'
    | '/_protectedLayout/books/'
    | '/_protectedLayout/borrowings/'
    | '/_protectedLayout/categories/'
    | '/_protectedLayout/dashboard/'
    | '/_protectedLayout/department/'
    | '/_protectedLayout/group/'
    | '/_protectedLayout/profile/'
    | '/_protectedLayout/shkolla/'
    | '/_protectedLayout/users/'
    | '/_publicLayout/about-us/'
    | '/_publicLayout/collections/'
    | '/_publicLayout/our-mission/'
    | '/_publicLayout/services/'
    | '/_protectedLayout/books/$id/'
    | '/_protectedLayout/books/add/'
    | '/_publicLayout/collections/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_publicLayout': {
      id: '/_publicLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protectedLayout': {
      id: '/_protectedLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_publicLayout/': {
      id: '/_publicLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_authLayout/register': {
      id: '/_authLayout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthLayoutRegisterRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/login': {
      id: '/_authLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLayoutLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_publicLayout/services/': {
      id: '/_publicLayout/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof PublicLayoutServicesIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_publicLayout/our-mission/': {
      id: '/_publicLayout/our-mission/'
      path: '/our-mission'
      fullPath: '/our-mission/'
      preLoaderRoute: typeof PublicLayoutOurMissionIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_publicLayout/collections/': {
      id: '/_publicLayout/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof PublicLayoutCollectionsIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_publicLayout/about-us/': {
      id: '/_publicLayout/about-us/'
      path: '/about-us'
      fullPath: '/about-us/'
      preLoaderRoute: typeof PublicLayoutAboutUsIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_protectedLayout/users/': {
      id: '/_protectedLayout/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof ProtectedLayoutUsersIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/shkolla/': {
      id: '/_protectedLayout/shkolla/'
      path: '/shkolla'
      fullPath: '/shkolla/'
      preLoaderRoute: typeof ProtectedLayoutShkollaIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/profile/': {
      id: '/_protectedLayout/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProtectedLayoutProfileIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/group/': {
      id: '/_protectedLayout/group/'
      path: '/group'
      fullPath: '/group/'
      preLoaderRoute: typeof ProtectedLayoutGroupIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/department/': {
      id: '/_protectedLayout/department/'
      path: '/department'
      fullPath: '/department/'
      preLoaderRoute: typeof ProtectedLayoutDepartmentIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/dashboard/': {
      id: '/_protectedLayout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedLayoutDashboardIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/categories/': {
      id: '/_protectedLayout/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof ProtectedLayoutCategoriesIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/borrowings/': {
      id: '/_protectedLayout/borrowings/'
      path: '/borrowings'
      fullPath: '/borrowings/'
      preLoaderRoute: typeof ProtectedLayoutBorrowingsIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/books/': {
      id: '/_protectedLayout/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof ProtectedLayoutBooksIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_publicLayout/collections/$id/': {
      id: '/_publicLayout/collections/$id/'
      path: '/collections/$id'
      fullPath: '/collections/$id/'
      preLoaderRoute: typeof PublicLayoutCollectionsIdIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_protectedLayout/books/add/': {
      id: '/_protectedLayout/books/add/'
      path: '/books/add'
      fullPath: '/books/add/'
      preLoaderRoute: typeof ProtectedLayoutBooksAddIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/books/$id/': {
      id: '/_protectedLayout/books/$id/'
      path: '/books/$id'
      fullPath: '/books/$id/'
      preLoaderRoute: typeof ProtectedLayoutBooksIdIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutLoginRoute: typeof AuthLayoutLoginRoute
  AuthLayoutRegisterRoute: typeof AuthLayoutRegisterRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutLoginRoute: AuthLayoutLoginRoute,
  AuthLayoutRegisterRoute: AuthLayoutRegisterRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface ProtectedLayoutRouteChildren {
  ProtectedLayoutBooksIndexRoute: typeof ProtectedLayoutBooksIndexRoute
  ProtectedLayoutBorrowingsIndexRoute: typeof ProtectedLayoutBorrowingsIndexRoute
  ProtectedLayoutCategoriesIndexRoute: typeof ProtectedLayoutCategoriesIndexRoute
  ProtectedLayoutDashboardIndexRoute: typeof ProtectedLayoutDashboardIndexRoute
  ProtectedLayoutDepartmentIndexRoute: typeof ProtectedLayoutDepartmentIndexRoute
  ProtectedLayoutGroupIndexRoute: typeof ProtectedLayoutGroupIndexRoute
  ProtectedLayoutProfileIndexRoute: typeof ProtectedLayoutProfileIndexRoute
  ProtectedLayoutShkollaIndexRoute: typeof ProtectedLayoutShkollaIndexRoute
  ProtectedLayoutUsersIndexRoute: typeof ProtectedLayoutUsersIndexRoute
  ProtectedLayoutBooksIdIndexRoute: typeof ProtectedLayoutBooksIdIndexRoute
  ProtectedLayoutBooksAddIndexRoute: typeof ProtectedLayoutBooksAddIndexRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedLayoutBooksIndexRoute: ProtectedLayoutBooksIndexRoute,
  ProtectedLayoutBorrowingsIndexRoute: ProtectedLayoutBorrowingsIndexRoute,
  ProtectedLayoutCategoriesIndexRoute: ProtectedLayoutCategoriesIndexRoute,
  ProtectedLayoutDashboardIndexRoute: ProtectedLayoutDashboardIndexRoute,
  ProtectedLayoutDepartmentIndexRoute: ProtectedLayoutDepartmentIndexRoute,
  ProtectedLayoutGroupIndexRoute: ProtectedLayoutGroupIndexRoute,
  ProtectedLayoutProfileIndexRoute: ProtectedLayoutProfileIndexRoute,
  ProtectedLayoutShkollaIndexRoute: ProtectedLayoutShkollaIndexRoute,
  ProtectedLayoutUsersIndexRoute: ProtectedLayoutUsersIndexRoute,
  ProtectedLayoutBooksIdIndexRoute: ProtectedLayoutBooksIdIndexRoute,
  ProtectedLayoutBooksAddIndexRoute: ProtectedLayoutBooksAddIndexRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

interface PublicLayoutRouteChildren {
  PublicLayoutIndexRoute: typeof PublicLayoutIndexRoute
  PublicLayoutAboutUsIndexRoute: typeof PublicLayoutAboutUsIndexRoute
  PublicLayoutCollectionsIndexRoute: typeof PublicLayoutCollectionsIndexRoute
  PublicLayoutOurMissionIndexRoute: typeof PublicLayoutOurMissionIndexRoute
  PublicLayoutServicesIndexRoute: typeof PublicLayoutServicesIndexRoute
  PublicLayoutCollectionsIdIndexRoute: typeof PublicLayoutCollectionsIdIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicLayoutIndexRoute: PublicLayoutIndexRoute,
  PublicLayoutAboutUsIndexRoute: PublicLayoutAboutUsIndexRoute,
  PublicLayoutCollectionsIndexRoute: PublicLayoutCollectionsIndexRoute,
  PublicLayoutOurMissionIndexRoute: PublicLayoutOurMissionIndexRoute,
  PublicLayoutServicesIndexRoute: PublicLayoutServicesIndexRoute,
  PublicLayoutCollectionsIdIndexRoute: PublicLayoutCollectionsIdIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
